name: Add Issue to Project Todo Column

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project Todo column
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          my_org="thomasthorntoncloud"
          my_num=2
          gh api graphql -f query='
            query($organization: String! $number: Int!){
              organization(login: $organization){
                organization(number: $number) {
                  id
                }
              }
            }' -f organization=$my_org -F number=$my_num