name: Add Issue to Project Todo Column

on:
  issues:
    types:
      - opened

# jobs:
  # open-issue:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     issues: write
  #   steps:
  #     - run: |
  #         gh issue --repo ${{ github.repository }} \
  #           create --title "Issue title" --body "Issue body"
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project Todo column
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            query{
              organization(login: "thomasthorntoncloud"){
                projectV2(number: 1) {
                  id
                }
              }
            }'

          # Add the issue to the project
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }
          ' -f project=$PROJECT_ID -f issue=$ISSUE_ID