name: Add Issue to Project Todo Column

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project Todo column
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            query($organization: String!) {
              organization(login: $organization) {
                projectsV2(first: 20) {
                  nodes {
                    id
                    number
                    title
                  }
                }
              }
            }
          ' -f organization=thomasthorntoncloud