name: Move Issue to Done When Closed

on:
  issues:
    types:
      - closed

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Done
        env:
          GH_TOKEN: ${{ secrets.SECRET_PAT }}
          ORGANIZATION: thomasthorntoncloud
          PROJECT_NUMBER: 1
        run: |
          # Get project ID
          PROJECT_ID=$(gh project view $PROJECT_NUMBER --owner $PROJECT_OWNER --format json | jq -r '.id')
          echo "Project ID: $PROJECT_ID"

          echo "All fields:"
          echo "$FIELDS" | jq '.'

          # # List project fields to find Status field
          # FIELDS=$(gh project field-list $PROJECT_NUMBER --owner $ORGANIZATION --format json)
          # STATUS_FIELD=$(echo "$FIELDS" | jq -r '.[] | select(.name == "Status")')
          # STATUS_FIELD_ID=$(echo "$STATUS_FIELD" | jq -r '.id')
          # DONE_OPTION_ID=$(echo "$STATUS_FIELD" | jq -r '.options[] | select(.name == "Done") | .id')
          # echo "STATUS_FIELD_ID: $STATUS_FIELD_ID"
          # echo "DONE_OPTION_ID: $DONE_OPTION_ID"

          # # List project items with pagination to find the closed issue
          # ITEM_ID=""
          # CURSOR=""
          # while [ -z "$ITEM_ID" ]; do
          #   ITEMS=$(gh project item-list $PROJECT_NUMBER --owner $ORGANIZATION --format json --limit 100 ${CURSOR:+--cursor "$CURSOR"})
          #   ITEM_ID=$(echo "$ITEMS" | jq -r --arg ISSUE_NUMBER "${{ github.event.issue.number }}" '.items[] | select(.content.number == ($ISSUE_NUMBER | tonumber)) | .id')
            
          #   if [ -n "$ITEM_ID" ]; then
          #     break
          #   fi
            
          #   CURSOR=$(echo "$ITEMS" | jq -r '.pageInfo.endCursor')
          #   if [ "$CURSOR" = "null" ]; then
          #     break
          #   fi
          # done

          # echo "ITEM_ID: $ITEM_ID"

          # if [ -z "$ITEM_ID" ]; then
          #   echo "Error: Could not find the issue in the project. Skipping status update."
          #   exit 0
          # fi

          # # Update the item's Status to Done
          # gh project item-edit $PROJECT_NUMBER --owner $ORGANIZATION --id "$ITEM_ID" --field-id "$STATUS_FIELD_ID" --single-select-option-id "$DONE_OPTION_ID"

          # echo "Issue successfully moved to Done status."

      - name: Confirm status update
        if: success()
        run: echo "Issue moved to Done status successfully."