name: Move Issue to In Progress When Reopened

on:
  issues:
    types:
      - reopened

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          ORGANIZATION: thomasthorntoncloud
          PROJECT_NUMBER: 1
        run: |
          # Retrieve project ID
          PROJECT_ID=$(gh api graphql -f query='
            query($organization: String!, $number: Int!) {
              organization(login: $organization) {
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organization=$ORGANIZATION -F number=$PROJECT_NUMBER --jq '.data.organization.projectV2.id')


          echo "PROJECT_ID: $PROJECT_ID"

          # Get the Status field ID and In Progress option ID
          FIELD_DATA=$(gh api graphql -f query='
            query($project: ID!) {
              node(id: $project) {
                ... on ProjectV2 {
                  fields(first: 20) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f project=$PROJECT_ID --jq '.data.node.fields.nodes[] | select(.name == "Status")')

          STATUS_FIELD_ID=$(echo "$FIELD_DATA" | jq -r '.id')
          IN_PROGRESS_OPTION_ID=$(echo "$FIELD_DATA" | jq -r '.options[] | select(.name == "In Progress") | .id')

          echo "STATUS_FIELD_ID: $STATUS_FIELD_ID"
          echo "IN_PROGRESS_OPTION_ID: $IN_PROGRESS_OPTION_ID"

            # Find the item ID for the reopened issue, accommodating more than 100 items
            ITEM_ID=$(gh api graphql -f query='
            query($project: ID!) {
              node(id: $project) {
              ... on ProjectV2 {
                items(first: 100) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                nodes {
                  id
                  content {
                  ... on Issue {
                    id
                  }
                  }
                }
                }
              }
              }
            }' -f project=$PROJECT_ID --jq '.data.node.items.nodes[] | select(.content.id == env.ISSUE_ID) | .id')

            # If not found, paginate through the rest of the items
            while [ -z "$ITEM_ID" ] && [ "$(echo "$PAGE_INFO" | jq -r '.hasNextPage')" == "true" ]; do
            PAGE_INFO=$(gh api graphql -f query='
              query($project: ID!, $cursor: String!) {
              node(id: $project) {
                ... on ProjectV2 {
                items(first: 100, after: $cursor) {
                  pageInfo {
                  hasNextPage
                  endCursor
                  }
                  nodes {
                  id
                  content {
                    ... on Issue {
                    id
                    }
                  }
                  }
                }
                }
              }
              }' -f project=$PROJECT_ID -f cursor=$(echo "$PAGE_INFO" | jq -r '.endCursor') --jq '.data.node.items.pageInfo')

            ITEM_ID=$(gh api graphql -f query='
              query($project: ID!, $cursor: String!) {
              node(id: $project) {
                ... on ProjectV2 {
                items(first: 100, after: $cursor) {
                  nodes {
                  id
                  content {
                    ... on Issue {
                    id
                    }
                  }
                  }
                }
                }
              }
              }' -f project=$PROJECT_ID -f cursor=$(echo "$PAGE_INFO" | jq -r '.endCursor') --jq '.data.node.items.nodes[] | select(.content.id == env.ISSUE_ID) | .id')
            done

          echo "ITEM_ID: $ITEM_ID"

          if [ -z "$ITEM_ID" ]; then
            echo "Error: Could not find the issue in the project. Skipping status update."
            exit 0
          fi

          # Set the Status to In Progress
          RESULT=$(gh api graphql -f query='
            mutation($project: ID!, $item: ID!, $field: ID!, $value: String!) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $field
                value: { 
                  singleSelectOptionId: $value
                }
              }) {
                projectV2Item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f field=$STATUS_FIELD_ID -f value=$IN_PROGRESS_OPTION_ID)

          if echo "$RESULT" | jq -e '.data.updateProjectV2ItemFieldValue.projectV2Item.id' > /dev/null; then
            echo "Issue successfully moved to In Progress status."
          else
            echo "Error updating issue status: $RESULT"
            exit 1
          fi

      - name: Confirm status update
        if: success()
        run: echo "Issue moved to In Progress status successfully."