name: Add Issue to Project Todo Column

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
      ISSUE_ID: ${{ github.event.issue.node_id }}
      PROJECT_OWNER: thomasthorntoncloud
      PROJECT_NUMBER: 1
    steps:
      - name: Add issue to project Todo column
        run: |
          # Get project ID
          PROJECT_ID=$(gh project view $PROJECT_NUMBER --owner $PROJECT_OWNER --format json | jq -r '.id')
          echo "Project ID: $PROJECT_ID"

          # Add issue to project
          FIELDS=$(gh project field-list $PROJECT_NUMBER --owner $PROJECT_OWNER --format json)
          echo "All fields:"
          echo "$FIELDS" | jq '.'

          STATUS_FIELD=$(echo "$FIELDS" | jq -r '.fields[] | select(.name == "Status")')
          STATUS_FIELD_ID=$(echo "$STATUS_FIELD" | jq -r '.id')
          TODO_OPTION_ID=$(echo "$STATUS_FIELD" | jq -r '.options[] | select(.name == "Todo") | .id')
          
          echo "STATUS_FIELD_ID: $STATUS_FIELD_ID"
          echo "TODO_OPTION_ID: $TODO_OPTION_ID"

          # Find the item ID for the closed issue, accommodating more than 100 items
          ITEM_ID=""
          CURSOR=""
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          while [ -z "$ITEM_ID" ]; do
            echo "Fetching items with cursor: $CURSOR"
            ITEMS_RESPONSE=$(gh project item-list $PROJECT_NUMBER --owner $PROJECT_OWNER --format json --limit 100 ${CURSOR:+--cursor "$CURSOR"})
            
            # Extract the item ID if the issue is found
            ITEM_ID=$(echo "$ITEMS_RESPONSE" | jq -r --arg ISSUE_NUMBER "$ISSUE_NUMBER" '.items[] | select(.content.number == ($ISSUE_NUMBER | tonumber)) | .id')
            
            if [ -n "$ITEM_ID" ]; then
              echo "Item found with ID: $ITEM_ID"
              break
            fi
            
            # Check if there are more pages
            HAS_NEXT_PAGE=$(echo "$ITEMS_RESPONSE" | jq -r '.pageInfo.hasNextPage')
            CURSOR=$(echo "$ITEMS_RESPONSE" | jq -r '.pageInfo.endCursor')
            
            if [ "$HAS_NEXT_PAGE" != "true" ] || [ "$CURSOR" = "null" ]; then
              echo "No more pages to fetch"
              break
            fi
          done

          if [ -z "$ITEM_ID" ]; then
            echo "Error: Could not find the issue in the project. Skipping status update."
            exit 0
          fi

          echo "ITEM_ID: $ITEM_ID"

          # Set the Status to ToDo
          echo "Updating item status to Done..."
          RESULT=$(gh project item-edit $PROJECT_NUMBER \
            --id "$ITEM_ID" \
            --project-id "$PROJECT_ID" \
            --field-id "$STATUS_FIELD_ID" \
            --single-select-option-id "$TODO_OPTION_ID" \
            --format json)

          if echo "$RESULT" | jq -e '.id' > /dev/null; then
            echo "Issue successfully moved to Done status."
          else
            echo "Error updating issue status: $RESULT"
            exit 1
          fi